services:
  - type: web
    name: emotion-backend
    env: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free

  - type: static
    name: emotion-frontend
    rootDir: frontend
    staticPublishPath: ./
    plan: free
